### ISSUE TITLE
将MathJax引入到MkDocs框架中的问题

### ISSUE THREAD

**Issue by yliu-fe** [Yang-Xijie/yang-xijie.github.io#18]
杨老师您好，因为近期有构建个人在线文档和博客的需求，在B站上看了您的MkDocs教程，目前看来比较安好，除了数学符号。
1. 根据Material for MkDocs文档的指引，我在mkdocs.yml里加入了`markdown_extensions`和`extra_javascript`两个部分，也创建了mathjax.js文件并挂在了mkdocs.yml里，但数学公式测试不能渲染。
2. 进一步，根据您在该仓库下的相关设置和指引（MfM文档中给出的原有cdn无法使用），我将原有的cdn改为了`unpkg.com/...`的那一个，并且按照规范将所有的现有网页挂在mkdocs.yml的`nav`下，
3. 考虑到原有`mathjax.js`规定的行内和行外公式分别由`\( ... \)`和`\[ ... \]`引导，而我个人的习惯是`$ ... $`和`$$ ... $$`，我于是修改了该文件中的对应两行，刷新后仍然未果。

现在我不知道该怎么解决该问题了，我将相关代码贴在下面，希望您能指点一二：

mkdocs.yml中的相关部分:
```
  markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences


  extra_javascript:
    - javascripts/mathjax.js  # 该文件的相对位置是"docs/javascripts/mathjax.js" 
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 
```

mathjax.js，除以下两行外，其他内容与您仓库中对应文件一致。
```
      inlineMath: [["$", "$"]],
      displayMath: [["$$", "$$"]],
```
